#!/usr/bin/env python3
# Copyright (c) 2026 Nimesh Patel. MIT Licence. https://github.com/91nimeshpatel/KMP-Arch
"""Generate the module dependency graph from the build files.

The graph used to be written by hand in three places. Three hand-maintained copies of one fact
drift within a month, and a wrong diagram is worse than none because the next reader reasons from
it. So it is derived from the only thing that cannot lie — the `project(":…")` declarations Gradle
actually resolves — and written between markers into every document that shows it.

    python3 tools/module-graph.py           # rewrite the documents
    python3 tools/module-graph.py --check   # fail if they are out of date

`ModuleGraphTest` runs `--check`, so a document can never disagree with the build again.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEGIN = "<!-- module-graph:begin -->"
END = "<!-- module-graph:end -->"

# Dependencies a module gets from a convention plugin rather than its own build file. They are real
# edges — a feature genuinely depends on these — so leaving them out would make the graph a lie of
# omission. Keep in step with build-logic/.../KmpFeatureConventionPlugin.kt.
CONVENTION = {
    "template.kmp.feature": [
        ":core:designsystem", ":core:ui", ":core:model", ":core:domain", ":core:testing",
    ],
}

STYLE = {
    ":androidApp": "app", ":composeApp": "shell",
    ":core:domain": "domain", ":core:data": "data",
    ":core:database": "source", ":core:network": "source", ":core:datastore": "source",
    ":core:designsystem": "ui", ":core:ui": "ui",
    ":core:model": "base", ":core:common": "base", ":core:platform": "base",
    ":core:testing": "testing",
}


def node_id(path: str) -> str:
    return path.strip(":").replace(":", "_").replace("-", "_")


def read_graph() -> dict[str, list[str]]:
    graph: dict[str, list[str]] = {}
    for build in sorted(ROOT.glob("*/build.gradle.kts")) + sorted(ROOT.glob("*/*/build.gradle.kts")):
        if "build-logic" in build.parts or build.parent == ROOT:
            continue
        module = ":" + str(build.parent.relative_to(ROOT)).replace("/", ":")
        text = build.read_text(encoding="utf-8")
        deps = re.findall(r'project\("(:[^"]+)"\)', text)
        for plugin, extra in CONVENTION.items():
            if f'id("{plugin}")' in text:
                deps += extra
        graph[module] = sorted(set(deps))
    return graph


def mermaid(graph: dict[str, list[str]]) -> str:
    modules = sorted(set(graph) | {d for deps in graph.values() for d in deps})
    lines = ["```mermaid", "graph TD"]
    for m in modules:
        style = STYLE.get(m, "base")
        lines.append(f'    {node_id(m)}["{m}"]:::{style}')
    lines.append("")
    lines.append('    iosApp["iosApp (Xcode)"]:::app')
    lines.append("    iosApp -.->|links ComposeApp.framework| composeApp")
    lines.append("")
    for m in modules:
        for d in graph.get(m, []):
            lines.append(f"    {node_id(m)} --> {node_id(d)}")
    lines += [
        "",
        "    classDef app fill:#1f5fd1,stroke:#00306b,color:#fff",
        "    classDef shell fill:#3b7dd8,stroke:#00306b,color:#fff",
        "    classDef feature fill:#a9c8ff,stroke:#1f5fd1,color:#00306b",
        "    classDef domain fill:#d7e3ff,stroke:#1f5fd1,color:#00306b",
        "    classDef data fill:#a9c8ff,stroke:#1f5fd1,color:#00306b",
        "    classDef source fill:#e8eefc,stroke:#5b7fc7,color:#00306b",
        "    classDef ui fill:#efe7fb,stroke:#7a5bc7,color:#2a1a52",
        "    classDef base fill:#f1f3f6,stroke:#8b97a8,color:#11161c",
        "    classDef testing fill:#fdf3e3,stroke:#b38b3a,color:#4a3510",
        "```",
    ]
    return "\n".join(lines)


def block(graph: dict[str, list[str]]) -> str:
    return (
        f"{BEGIN}\n"
        "<!-- Generated by tools/module-graph.py from the build files. Do not edit by hand:\n"
        "     run `python3 tools/module-graph.py` after changing a module dependency. -->\n\n"
        f"{mermaid(graph)}\n\n{END}"
    )


def main() -> int:
    check = "--check" in sys.argv
    graph = read_graph()
    want = block(graph)
    stale: list[str] = []

    for doc in ("README.md", "docs/ARCHITECTURE.md", ".claude/rules/architecture.md"):
        path = ROOT / doc
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        if BEGIN not in text:
            continue
        current = text[text.index(BEGIN):text.index(END) + len(END)]
        if current == want:
            continue
        if check:
            stale.append(doc)
        else:
            path.write_text(text.replace(current, want), encoding="utf-8")
            print(f"updated {doc}")

    if stale:
        print("Out of date: " + ", ".join(stale), file=sys.stderr)
        print("Run: python3 tools/module-graph.py", file=sys.stderr)
        return 1
    if check:
        print("module graph is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
